version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_HTTP=${API_HTTP}
      - GATEWAY_HOST=${GATEWAY_HOST}
      - COMMON_PREFIX=${COMMON_PREFIX}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped